package ma.eshop.auth;

import javax.sql.DataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Initialise la table {@code USERS} (site global) et y insere les deux comptes
 * de demonstration au demarrage.
 *
 * <p>Equivalent d'un {@code data.sql}, mais en Java : cela permet de
 * <strong>hasher les mots de passe en BCrypt au runtime</strong> (impossible a
 * faire de maniere fiable dans un script SQL statique) et reste idempotent —
 * la table n'est creee que si elle manque et les comptes ne sont ajoutes que
 * s'ils n'existent pas deja.</p>
 *
 * <p>Comptes de test crees :</p>
 * <ul>
 *   <li>{@code admin / admin123} — role ADMIN</li>
 *   <li>{@code user1 / user123} — role USER</li>
 * </ul>
 */
@Configuration
public class DataInitializer {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    private static final String CREATE_USERS_TABLE = """
            CREATE TABLE USERS (
              ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              USERNAME VARCHAR2(50)  NOT NULL UNIQUE,
              PASSWORD VARCHAR2(100) NOT NULL,
              ROLE     VARCHAR2(20)  NOT NULL
            )""";

    /**
     * Runner execute au demarrage : DDL idempotente + seed des comptes de test.
     *
     * @param globalDataSource datasource du site global (primaire)
     * @param userRepository   repository des comptes
     * @param passwordEncoder  encodeur BCrypt
     * @return le runner d'initialisation
     */
    @Bean
    public ApplicationRunner authDataInitializer(
            @Qualifier("globalDataSource") DataSource globalDataSource,
            UserRepository userRepository,
            PasswordEncoder passwordEncoder) {

        return args -> {
            JdbcTemplate jdbc = new JdbcTemplate(globalDataSource);
            ensureUsersTable(jdbc);

            seedUser(userRepository, passwordEncoder, "admin", "admin123", "ADMIN");
            seedUser(userRepository, passwordEncoder, "user1", "user123", "USER");
        };
    }

    /** Cree la table USERS si elle n'existe pas encore (verifie le catalogue). */
    private void ensureUsersTable(JdbcTemplate jdbc) {
        Integer count = jdbc.queryForObject(
                "SELECT COUNT(*) FROM user_tables WHERE table_name = 'USERS'",
                Integer.class);
        if (count != null && count > 0) {
            log.info("Table USERS deja presente : creation ignoree.");
            return;
        }
        jdbc.execute(CREATE_USERS_TABLE);
        log.info("Table USERS creee sur le site global.");
    }

    /** Insere un compte s'il n'existe pas deja (mot de passe hashe BCrypt). */
    private void seedUser(UserRepository repository, PasswordEncoder encoder,
                          String username, String rawPassword, String role) {
        if (repository.existsByUsername(username)) {
            return;
        }
        repository.save(new User(username, encoder.encode(rawPassword), role));
        log.info("Compte de demonstration cree : {} (role {}).", username, role);
    }
}
